# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Charybdis'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["bastardkb/charybdis/4x6/v2/splinky_3"]'
      mapping: '["via"]'
